### PR TITLE
LPS-73142 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
@p2kmgcl podrías comprobar que todo funciona bien después de mis cambios?

**Comment by p2kmgcl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
👍

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/liferay/com-liferay-journal/pull/377. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
